openapi: 3.0.3
info:
  title: students - OpenAPI 3.0
  description: |-
    students API Spec
  version: 1.0.0
servers:
  - url: api/v1
tags: 
  - name: students
    description: Category related API
paths:
  /students:
      get:
       tags:
        - students
       summary: Get all students
       description: Get all students
       operationId: getStudents
       responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Student'          
          '400':
            description: Invalid request
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 10
        name:
          type: string
          example: John
        grade:
          type: integer
          format: int
          example: 25